config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"
  get "static_pages/help"
  get "orders_active", to: "orders#active"

  resources :books
  resources :publishers
  resources :authors
  resources :carts
  resources :orders
  resources :line_items
  resources :users
  
  delete 'admin/users/:id' => 'admin/users#destroy', :via => :delete, :as => :admin_destroy_user
  delete 'admin/authors/:id' => 'admin/authors#destroy', :via => :delete, :as => :admin_destroy_author
  delete 'admin/publishers/:id' => 'admin/publishers#destroy', :via => :delete, :as => :admin_destroy_publisher
  delete 'admin/books/:id' => 'admin/books#destroy', :via => :delete, :as => :admin_destroy_book

  namespace :admin do
    resources :books
    resources :authors
    resources :publishers
    resources :users
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books, dependent: :destroy
  has_many :books, through: :author_book

  validates :name, presence: true, length: { maximum: 20 }
  validates :country, presence: true
  validates :age, presence: true
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController
  before_action :get_author, only: [:show, :update, :destroy, :edit]

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author successfully created"
      redirect_to admin_authors_path
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    if @author.update(author_params)
      flash[:success] = "Author updated"
      redirect_to admin_authors_path
    else
      render 'edit'
    end
  end

  def destroy
    if @author.present?
      @author.destroy
      flash[:success] = "Author deleted"
    else
      flash[:error] = "Can not delete author!"
    end
    redirect_to admin_authors_url
  end

  private

  def get_author
    @author = Author.find_by(id: params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :country, :age)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find_by(id: params[:id])
  end
end

app/views/admin/authors/edit.html.erb
<h2>Update Author</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3-edit-user">
    <%= form_for :author, url: {action: :update, controller: :authors}, method: :put do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :country %>
      <%= f.text_field :country, class: "form-control" %>
      <%= f.label :age %><br />
      <%= f.number_field :age, class: "form-control" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Update author</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/authors/index.html.erb
<% provide(:title, "All authors") %>
<h1>All authors</h1>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">Stt</th>
        <th scope="col">Name</th>
        <th scope="col">Country</th>
        <th scope="col">Age</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
  <% @authors.each_with_index do |author, index| %>
  <tbody>
    <tr>
      <th scope="row"><%=index +1 %></th>
      <td> <%= link_to author.name, author %> </td>
      <td> <%= author.country %> </td>
      <td> <%= author.age %> </td>
      <td>
        <%= link_to author_path(author) do %>
          <i class="fa fa-eye "  ></i>
        <% end %>
        <%= link_to edit_admin_author_path(author) do %>
          <i class="fa fa-pencil icon_edit" aria-hidden="true" ></i>
        <% end %>
        <%= link_to admin_destroy_author_path(author), method: :delete do %>
          <i class="fa fa-trash icon_delete" ></i>
        <% end %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/admin/authors/new.html.erb
<%provide(:title, "Create Author")%>
<h1>Create Author</h1>
<div class="row">
  <div class="form-group col-md-6">
    <%= form_for @author, url: admin_authors_path, method: :post do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :country %><br />
      <%= f.text_field :country, class: "form-control" %>
      <%= f.label :age %><br />
      <%= f.number_field :age, class: "form-control" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Create author</button>
          <%= link_to "Back", new_admin_book_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>