config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"
  get "static_pages/help"
  get "orders_active", to: "orders#active"

  resources :books
  resources :publishers
  resources :authors
  resources :carts
  resources :orders
  resources :line_items
  resources :users
  
  delete 'admin/users/:id' => 'admin/users#destroy', :via => :delete, :as => :admin_destroy_user
  delete 'admin/authors/:id' => 'admin/authors#destroy', :via => :delete, :as => :admin_destroy_author
  delete 'admin/publishers/:id' => 'admin/publishers#destroy', :via => :delete, :as => :admin_destroy_publisher
  delete 'admin/books/:id' => 'admin/books#destroy', :via => :delete, :as => :admin_destroy_book

  namespace :admin do
    resources :books
    resources :authors
    resources :publishers
    resources :users
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :book_publishers, dependent: :destroy
  has_many :books, through: :book_publisher

  validates :name, presence: true, length: {maximum: 30 }
  validates :address, presence: true, length: {maximum: 30}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < AdminController
  before_action :get_publisher, only: [:show, :update, :destroy, :edit]

  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:success] = "Publisher successfully created"
      redirect_to admin_publishers_path
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      flash[:success] = "Publisher updated"
      redirect_to admin_publishers_path
    else
      render 'edit'
    end
  end

  def destroy
    if @publisher.present?
      @publisher.destroy
      flash[:success] = "Publisher deleted"
    else
      flash[:error] = "Can not delete publisher!"
    end
    redirect_to admin_publishers_url
  end

  private

  def get_publisher
    @publisher = Publisher.find_by(id: params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name, :address)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def show
    @publisher = Publisher.find_by(id: params[:id])
  end
end

app/views/admin/publishers/edit.html.erb
<h2>Update Author</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3-edit-user">
    <%= form_for :publisher, url: {action: :update, controller: :publishers}, method: :put do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Update publisher</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/publishers/index.html.erb
<% provide(:title, "All publishers") %>
<h1>All publishers</h1>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th scope="col">Stt</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Actions</th>
      </tr>
  </thead>
  <% @publishers.each_with_index do |publisher, index| %>
    <tbody>
      <tr>
        <th scope="row"><%= index +1 %></th>
        <td> <%= link_to publisher.name, publisher %> </td>
        <td> <%= publisher.address %> </td>
        <td>
          <%= link_to publisher_path(publisher) do %>
            <i class="fa fa-eye "  ></i>
          <% end %>
          <%= link_to edit_admin_publisher_path(publisher.id) do %>
            <i class="fa fa-pencil icon_edit" aria-hidden="true" ></i>
          <% end %>
          <%= link_to admin_destroy_publisher_path(publisher), method: :delete do %>
            <i class="fa fa-trash icon_delete" ></i>
          <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/publishers/new.html.erb
<%provide(:title, "Create Publisher")%>
<h1>Create Publisher</h1>
<div class="row">
  <div class="form-group col-md-6">
    <%= form_for @publisher, url: admin_publishers_path, method: :post do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :address %><br />
      <%= f.text_field :address, class: "form-control" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Create publisher</button>
          <%= link_to "Back", new_admin_book_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>