config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"
  get "static_pages/help"
  get "orders_active", to: "orders#active"

  resources :books
  resources :publishers
  resources :authors
  resources :carts
  resources :orders
  resources :line_items
  resources :users
  
  delete 'admin/users/:id' => 'admin/users#destroy', :via => :delete, :as => :admin_destroy_user
  delete 'admin/authors/:id' => 'admin/authors#destroy', :via => :delete, :as => :admin_destroy_author
  delete 'admin/publishers/:id' => 'admin/publishers#destroy', :via => :delete, :as => :admin_destroy_publisher
  delete 'admin/books/:id' => 'admin/books#destroy', :via => :delete, :as => :admin_destroy_book

  namespace :admin do
    resources :books
    resources :authors
    resources :publishers
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_save :create_cart
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true , length: { minimum: 5 }
  validates :phone, presence: true, numericality: true

  has_many :books, dependent: :destroy
  has_one :cart
  enum role: { user:0, admin:1 }

  private

  def create_cart
    cart = Cart.create(user_id: self.id)
    cart
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :get_user, only: [:show, :update, :destroy, :edit]
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 5).order('created_at desc')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created"
      redirect_to admin_users_path
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    if @user.present? && !@user.admin?
      @user.destroy
      flash[:success] = "User destroyed."
    else
      flash[:error] = "Can not delete account!"
    end
    redirect_to admin_users_url
  end

  private

  def get_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
  params.require(:user).permit(:name, :email, :role, :phone, :password, :password_confirmation ) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/views/admin/users/edit.html.erb
<h2>Update User</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3-edit-user">
    <%= form_for :user, url: {action: :update, controller: :users}, method: :put do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :phone %><br />
      <%= f.telephone_field :phone, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.label "User" %>
      <%= f.radio_button(:role, "user") %>
      <%= f.label "Admin", class: "label_role" %>
      <%= f.radio_button(:role, "admin") %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Update user</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, "All users") %>
<div style="display: flex; justify-content: space-between; align-items: center">
<h1>All users</h1>
<% if current_user.admin? %>
    <%= link_to "Create User", new_admin_user_path, class: "btn btn-primary" %>
  <% end %>
</div>
<table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">Stt</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Role</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
  <% @users.each_with_index do |user, index| %>
  <tbody>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td> <%= link_to user.name, user %> </td>
      <td> <%= user.email %> </td>
      <td> <%= user.phone %> </td>
      <td> <%= user.role %> </td>
      <td>
        <%= link_to user_path(user) do %>
          <i class="fa fa-eye "  ></i>
        <% end %>
        <%= link_to edit_admin_user_path(user.id) do %>
          <i class="fa fa-pencil icon_edit" aria-hidden="true" ></i>
        <% end %>
        <%= link_to admin_destroy_user_path(user), method: :delete, data: {confirm: "You sure?"} do %>
          <i class="fa fa-trash icon_delete" ></i>
        <% end %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
<p><%= will_paginate @users %></p>

app/views/admin/users/new.html.erb
<h2>Create user</h2>
<%= form_for @user, url:admin_users_path, method: :post do |f| %>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %><br />
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :phone %><br />
      <%= f.telephone_field :phone, class: "form-control" %>
      <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
      <%= f.label "User" %>
      <%= f.radio_button(:role, "user") %>
      <%= f.label "Admin", class: "label_role" %>
      <%= f.radio_button(:role, "admin") %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Create user</button>
    </div>
  </div>
<% end %>