config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"
  get "static_pages/help"
  get "orders_active", to: "orders#active"

  resources :books
  resources :publishers
  resources :authors
  resources :carts
  resources :orders
  resources :line_items
  resources :users
  
  delete 'admin/users/:id' => 'admin/users#destroy', :via => :delete, :as => :admin_destroy_user
  delete 'admin/authors/:id' => 'admin/authors#destroy', :via => :delete, :as => :admin_destroy_author
  delete 'admin/publishers/:id' => 'admin/publishers#destroy', :via => :delete, :as => :admin_destroy_publisher
  delete 'admin/books/:id' => 'admin/books#destroy', :via => :delete, :as => :admin_destroy_book

  namespace :admin do
    resources :books
    resources :authors
    resources :publishers
    resources :users
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Library Management", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user)  %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :get %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<% if current_user.present? %>
  <div id="sidebar">
    <header>
      <a href="#">My App</a>
    </header>
    <ul class="nav">
      <li>
      <a href="<%= books_path(@books)%>">
          <i class="zmdi zmdi-view-dashboard"></i> Book
      </a>
      </li>
      <li>
      <a href="<%= orders_path(@orders)%>">
          <i class="zmdi zmdi-link"></i> Order
      </a>
      </li>
      <% if user_signed_in? %>
      <li>
      <a href="<%= cart_path(current_cart) %>">
          <i class="zmdi zmdi-widgets"></i> Cart
      </a>
      </li>
      <% end %>
      <% if current_user&.admin? %>
        <li>
        <a href="<%= admin_users_path(@users) %>">
            <i class="zmdi zmdi-widgets"></i> User
        </a>
        </li>
        <li>
        <a href="<%= admin_authors_path(@authors) %>">
            <i class="zmdi zmdi-widgets"></i> Author
        </a>
        </li>
        <li>
        <a href="<%= admin_publishers_path(@publishers) %>">
            <i class="zmdi zmdi-widgets"></i> Publisher
        </a>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Library Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render 'layouts/sidebar' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Library Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>